// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package queue

import (
	"OneGfServer/api/queue"
)

type ControllerV1 struct{}

func NewV1() queue.IQueueV1 {
	return &ControllerV1{}
}
