// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"OneGfServer/internal/dao/internal"
)

// deviceLogsDao is the data access object for the table device_logs.
// You can define custom methods on it to extend its functionality as needed.
type deviceLogsDao struct {
	*internal.DeviceLogsDao
}

var (
	// DeviceLogs is a globally accessible object for table device_logs operations.
	DeviceLogs = deviceLogsDao{internal.NewDeviceLogsDao()}
)

// Add your custom methods and functionality below.
