// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"OneGfServer/internal/dao/internal"
)

// deviceQueueOperationHistoryDao is the data access object for the table device_queue_operation_history.
// You can define custom methods on it to extend its functionality as needed.
type deviceQueueOperationHistoryDao struct {
	*internal.DeviceQueueOperationHistoryDao
}

var (
	// DeviceQueueOperationHistory is a globally accessible object for table device_queue_operation_history operations.
	DeviceQueueOperationHistory = deviceQueueOperationHistoryDao{internal.NewDeviceQueueOperationHistoryDao()}
)

// Add your custom methods and functionality below.
