// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"OneGfServer/internal/dao/internal"
)

// deviceLoadMonitorDao is the data access object for the table device_load_monitor.
// You can define custom methods on it to extend its functionality as needed.
type deviceLoadMonitorDao struct {
	*internal.DeviceLoadMonitorDao
}

var (
	// DeviceLoadMonitor is a globally accessible object for table device_load_monitor operations.
	DeviceLoadMonitor = deviceLoadMonitorDao{internal.NewDeviceLoadMonitorDao()}
)

// Add your custom methods and functionality below.
