// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"OneGfServer/internal/dao/internal"
)

// deviceTaskQueueDao is the data access object for the table device_task_queue.
// You can define custom methods on it to extend its functionality as needed.
type deviceTaskQueueDao struct {
	*internal.DeviceTaskQueueDao
}

var (
	// DeviceTaskQueue is a globally accessible object for table device_task_queue operations.
	DeviceTaskQueue = deviceTaskQueueDao{internal.NewDeviceTaskQueueDao()}
)

// Add your custom methods and functionality below.
