// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"OneGfServer/internal/dao/internal"
)

// deviceCommandsDao is the data access object for the table device_commands.
// You can define custom methods on it to extend its functionality as needed.
type deviceCommandsDao struct {
	*internal.DeviceCommandsDao
}

var (
	// DeviceCommands is a globally accessible object for table device_commands operations.
	DeviceCommands = deviceCommandsDao{internal.NewDeviceCommandsDao()}
)

// Add your custom methods and functionality below.
