// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"OneGfServer/internal/dao/internal"
)

// deviceHeartbeatsDao is the data access object for the table device_heartbeats.
// You can define custom methods on it to extend its functionality as needed.
type deviceHeartbeatsDao struct {
	*internal.DeviceHeartbeatsDao
}

var (
	// DeviceHeartbeats is a globally accessible object for table device_heartbeats operations.
	DeviceHeartbeats = deviceHeartbeatsDao{internal.NewDeviceHeartbeatsDao()}
)

// Add your custom methods and functionality below.
