// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"OneGfServer/internal/dao/internal"
)

// deviceTasksDao is the data access object for the table device_tasks.
// You can define custom methods on it to extend its functionality as needed.
type deviceTasksDao struct {
	*internal.DeviceTasksDao
}

var (
	// DeviceTasks is a globally accessible object for table device_tasks operations.
	DeviceTasks = deviceTasksDao{internal.NewDeviceTasksDao()}
)

// Add your custom methods and functionality below.
