// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"OneGfServer/internal/dao/internal"
)

// taskAssignmentQueueDao is the data access object for the table task_assignment_queue.
// You can define custom methods on it to extend its functionality as needed.
type taskAssignmentQueueDao struct {
	*internal.TaskAssignmentQueueDao
}

var (
	// TaskAssignmentQueue is a globally accessible object for table task_assignment_queue operations.
	TaskAssignmentQueue = taskAssignmentQueueDao{internal.NewTaskAssignmentQueueDao()}
)

// Add your custom methods and functionality below.
