// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"OneGfServer/internal/dao/internal"
)

// taskAssignmentHistoryDao is the data access object for the table task_assignment_history.
// You can define custom methods on it to extend its functionality as needed.
type taskAssignmentHistoryDao struct {
	*internal.TaskAssignmentHistoryDao
}

var (
	// TaskAssignmentHistory is a globally accessible object for table task_assignment_history operations.
	TaskAssignmentHistory = taskAssignmentHistoryDao{internal.NewTaskAssignmentHistoryDao()}
)

// Add your custom methods and functionality below.
