// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"OneGfServer/internal/dao/internal"
)

// taskExecutionsDao is the data access object for the table task_executions.
// You can define custom methods on it to extend its functionality as needed.
type taskExecutionsDao struct {
	*internal.TaskExecutionsDao
}

var (
	// TaskExecutions is a globally accessible object for table task_executions operations.
	TaskExecutions = taskExecutionsDao{internal.NewTaskExecutionsDao()}
)

// Add your custom methods and functionality below.
